language: python
python:
  - "3.6.6"
install:
  - pip install -r requirements.txt
script:
  - pytest -cov=api/ 
  - coverage xml
  - coverage debug data
  - coverage3 report
  - coveralls  
after_success:
- coveralls
