language: python
python:
  - "3.6.6"
install:
  - pip install -r requirements.txt
script:
  - pytest
  - nosetests --with-coverage --cover-erase
  - coverage
  - coverage debug data
  - coverage report
after_success:
- coveralls
